name: Deploy Core Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/core/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'infra/core/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Bicep Linter
              run: az bicep build --file './infra/core/main.bicep'
    
    validate:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - uses: azure/arm-deploy@v2
              name: Run preflight validation
              with:
                deploymentName: ${{ github.run_number }}
                resourceGroupName: ${{ secrets.AZURE_RG }}
                template: ./infra/core/main.bicep
                parameters: ./infra/core/main.bicepparam email=${{ secrets.EMAIL}}
                deploymentMode: Validate

    preview:
        needs: validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - uses: Azure/cli@v2
              name: Run what-if
              with:
                inlineScript: |
                    az deployment group what-if --resource-group ${{ secrets.AZURE_RG }} --template-file ./infra/core/main.bicep --parameters ./infra/core/main.bicepparam email=${{ secrets.EMAIL}}
    
    deploy:
        needs: preview
        environment: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - uses: azure/arm-deploy@v2
              name: Deploy Bicep File
              with:
                deploymentName: ${{ github.run_number }}
                resourceGroupName: ${{ secrets.AZURE_RG }}
                template: ./infra/core/main.bicep
                parameters: ./infra/core/main.bicepparam email=${{ secrets.EMAIL}}